services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mynetwork
    environment:
      - DOCKER_ENV=true

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - ${USERPROFILE}/.modular_intelligence:/root/.modular_intelligence
    environment:
      - DATABASE=/root/.modular_intelligence/modular_intelligence.db

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - mynetwork

networks:
  mynetwork:
