services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mynetwork
    environment:
      - DOCKER_ENV=true

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - ${USERPROFILE}/.modular_intelligence/modular_intelligence.db:/root/.modular_intelligence/modular_intelligence.db
    environment:
      - DATABASE=/root/.modular_intelligence/modular_intelligence.db
      
networks:
  mynetwork:
